/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/

//

uint8_t value = 0b10110101;
uint8_t mask  = 0b00001111;
uint8_t mask2 = 0b11110000;
uint8_t result = 0;

uint8_t a = 0b00001111;
uint8_t result1=0;
uint8_t b= 0b10100101;
uint8_t result2=0;

uint8_t simulated_register= 0x00;
int main(void)
{
	/*************
	 EJERCICIO 2.1
	 ************/
	result=value & mask2; //0b10110000

	/*************
	 EJERCICIO 2.2
	 ************/
	value =  0b10100000;
	mask =   0b00000101;
	result = value | mask; //0b10100101;

	/*************
	 EJERCICIO 2.3
	 ************/
	result1 = ~a; //0b11110000
	result2 = ~b; //0b01011010

	value = 0b11111111;

	value &= ~(0b1 << 0); //0b11111110
	value &= ~(0b1 << 1); //0b11111100
	value &= ~(0b1 << 2); //0b11111000 ...

	/*************
	 EJERCICIO 2.4
	 ************/
	result1=0;
	result2=0;
	value= 0b10110011;
	mask=  0b00001111;

	result1= value ^ mask; //  0b10111100
	result2= result1 ^ mask; //0b10110011

	/*************
	 EJERCICIO 2.5
	 ************/

	simulated_register |= (0b00001100); //0b00001100

	simulated_register &= ~(0b00000100); //0b0001000

	simulated_register ^= (0b00001000); // 0b0000000

	simulated_register ^= (0b00001000); // 0b0001000

	/*************
	 EJERCICIO 2.6
	 ************/

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	/*************
	 EJERCICIO 2.7
	 ************/
	GPIOA->MODER &= ~(0b11<<10); //limpiamos los valores del moder
	GPIOA->MODER |=  (0b01<<10); // configuramos como salida
	GPIOA->ODR &= ~(0b1<<5); //limpiamos el ODR
	GPIOA->ODR |=  (0b1<<5);//establecemos el valor del ODR en 1 (pin con valor high)

    while(1){
    }

    return 0;
}



