/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/



int main(void)
{
	/***************
	 * EJERCICIO 3.2
	 ***************/

	// habilitamos señal de reloj GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	//habilitamos señal de reloj GPIOB
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;

	//deshabilitamos señal de reloj GPIOB
	RCC->AHB1ENR &= ~(RCC_AHB1ENR_GPIOBEN);

	/***************
	 * EJERCICIO 3.3
	 ***************/

	// habilitamos señal de reloj GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	// limpiamos el estado de los bits reservador para el puerto 5 del registro MODER del GPIOA
	GPIOA->MODER &= ~(0b11 <<10);
	// Establecemos PA 5 como salida (01)
	GPIOA->MODER |= (0b01 << 10);
	// Establecemos el tipo de salida como pull up - pull down (1)
	GPIOA->OTYPER &= ~(0b1 <<5);
	// Limpiamos el estado de la velocidad del pin
	GPIOA->OSPEEDR &= ~(0b11 << 10);
	// Establecemos la velocidad de conmutación en medio (01)
	GPIOA->OSPEEDR |= (0b01 << 10);
	// Limpiamos la configuración del registro PUPDR para establecer el estado no pull no pull down
	GPIOA->PUPDR &= ~(0b11 << 10);


	// Encendemos el LED
	GPIOA->ODR |= (0b1 << 5);

	/***************
	 * EJERCICIO 3.4
	 ***************/
	// habilitamos señal de reloj GPIOC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

	// limpiamos el estado de los bits reservados para el puerto 13 del registro MODER del GPIOA y lo dejamos en su valor 00 (input)
	GPIOC->MODER &= ~(0b11 << 26);

	// limpiamos el estado de los bits reservados para el puerto 13 del registro PUPDR del GPIOC
	GPIOC->PUPDR &= ~(0b11 << 26);

	// habilitamos la resistencia pull up en el pin 13 para definir en todo momento el valor lógico del pin
	GPIOC->PUPDR |= (0b01 <<26);

    while(1){
    }

    return 0;
}



