/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/


uint32_t value = 1600000;
int main(void){
	// habilitamos señal de reloj GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	// limpiamos el estado de los bits reservador para el puerto 5 del registro MODER del GPIOA
	GPIOA->MODER &= ~(0b11 <<10);
	// Establecemos PA 5 como salida (01)
	GPIOA->MODER |= (0b01 << 10);
	// Establecemos el tipo de salida como push-pull (1)
	GPIOA->OTYPER &= ~(0b1 <<5);
	// Limpiamos el estado de la velocidad del pin
	GPIOA->OSPEEDR &= ~(0b11 << 10);
	// Establecemos la velocidad de conmutación en medio (01)
	GPIOA->OSPEEDR |= (0b01 << 10);
	// Limpiamos la configuración del registro PUPDR para establecer el estado no pull no pull down
	GPIOA->PUPDR &= ~(0b11 << 10);






    while(1){
    	//toogle
    	GPIOA->ODR ^= GPIO_ODR_OD5;
    	//esperamos con un retardo de software
    	for(uint32_t i = 0; i < value; i++){}
    }
    return 0;
}




