/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/**#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif**/



int main(void)
{
    //1.1
    uint8_t a = 17;
    uint8_t b = 5;
    uint8_t div_result= a / b;  // 3
    uint8_t mod_result= a % b;  // 2
    uint8_t mul_result= a * b;  // 85

    //1.2
    uint8_t x = 200;
    uint8_t y = 100;
    uint8_t z = x + y; // 44

    //1.3
    uint8_t val = 3;
    uint8_t left1  = val << 1; //6
    uint8_t left2  = val << 2; //12
    uint8_t left3  = val << 3; //24
    uint8_t right1 = val >> 1; // 1
    uint8_t right2 = val >> 2; // 0

    //1.4
    uint8_t aa= 0b1;  //a=1
    uint8_t bb= 0b10; //b=2
    uint8_t cc= 0b11; //c=3
    uint8_t result= 0b0; //result=0

    //condicion =! 0
    if (aa){
        result=0b1010; //result = 10
    }

    //condicion == 0
    if (bb-2){

    } else{
        result=0b10100; // result = 20
    }

    //condicion a==b
    if (aa==bb){
    	//result == 30
    } else{
    	result=0b11110;//result == 30
    }

    //1.5
    uint8_t i = 0;
    uint8_t counter=0;
    //contador de uno en uno
    for (i=0;i<10;i++){
    	counter++;
    }

    //counter=10
    counter=0;
    //contador de 2 en 2
    for (i=0;i<10;i=i+2){
    	counter=i;
    }

    //counter=8
    counter=0;
    //contador de 10 a 1
    for (i=10;i>=1;i=i-1){
    	counter=i;
    }

    //counter=1
    counter=0;
    //contador de 10 a 3
    for (i=10;i>=3;i=i-1){
    	counter=i;
    }

    //counter=3
    counter=0;
    //contador de 1 a 3
    for (i=1;i<=3;i=i+1){
    	counter=i;
    }

    //counter=3

    //sumador hasta 10
    uint8_t sum=0;
    uint8_t j=1;
    while(j<=10){
    	sum=sum+j;
    	j++;
    }
    //sum=1+2+3+4+5+6+7+8+9+10
    //j=11
    //sumador hasta 100
    uint16_t sum2=0;
    j=1;
    while(j<=100){
        sum2=sum2+j;
        j++;
    }
    //j=101


    while(1){

    }

    return 0;
}



