/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/
// definimimos TIM2->CNT como una variable global para poder verla en live_expressions

uint32_t contador=0;
int main(void){

	/**************************
	 ***CONFIGURACIÓN LED_OK***
	 **************************/

	// Habilitamos señal de reloj GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	// Limpiamos el estado de los bits reservados para el puerto 5 del registro MODER del GPIOA
	GPIOA->MODER &= ~(0b11 <<10);
	// Establecemos PA 5 como salida (01)
	GPIOA->MODER |= (0b01 << 10);
	// Establecemos el tipo de salida como pull up - pull down (1)
	GPIOA->OTYPER &= ~(0b1 <<5);
	// Limpiamos el estado de la velocidad del pin
	GPIOA->OSPEEDR &= ~(0b11 << 10);
	// Establecemos la velocidad de conmutación en medio (01)
	GPIOA->OSPEEDR |= (0b01 << 10);
	// Limpiamos la configuración del registro PUPDR para establecer el estado no pull up no pull down
	GPIOA->PUPDR &= ~(0b11 << 10);

	/************************
	 ***CONFIGURACIÓN TIM2***
	 ************************/

	// Encender la señal de reloj del tim2
	RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;
	// Establecer el prescaler para que genere un pulso de 1ms
	TIM2->PSC = 15999;
	// Contar 500 pulsos para generar una señal de 2Hz
	TIM2->ARR = 499;
	// Limpiamos el contador
	TIM2->CNT = 0;
	// limpiamos la bandera del event-update
	TIM2->SR &= ~TIM_SR_UIF;
	// Activamos la interrupción del TIM2 por event-update
	TIM2->DIER |= TIM_DIER_UIE;
	// Matriculamos la interrupción del TIM2 en el NVIC
	NVIC_EnableIRQ(TIM2_IRQn);
	// Activamos el contador con timer 2
	TIM2->CR1 |= TIM_CR1_CEN;





    while(1){


    }
}


/******************
 ***HANDLER TIM2***
 ******************/
void TIM2_IRQHandler(){
	if (TIM2->SR & TIM_SR_UIF){

		// Toogle a LED_OK
		GPIOA->ODR ^= (0b1 << 5);

		// limpiamos la bandera del event-update
		TIM2->SR &= ~TIM_SR_UIF;
	}
}




